export { demoQuestions } from "@/lib/orgpilot-data";

export const exampleQuestions = [
  "Hi",
  "Hello",
  "Good morning",
  "What can you do?",
  "Help me find an owner",
  "Show me example questions",
  "Who owns the Travel Claims API?",
  "Who owns travel claims?",
  "Travel API owner?",
  "Who supports claims API?",
  "Travel claims service",
  "Who owns the Claims Event Stream?",
  "Claims stream owner?",
  "Who supports claims events?",
  "Which team owns claims orchestration?",
  "Who can approve Azure subscriptions?",
  "How do I request Azure approval?",
  "Which team manages Azure?",
  "Who handles cloud approval workflows?",
  "Who reviews landing zone exceptions?",
  "Who knows Kotlin Multiplatform?",
  "Find a KMP expert",
  "Who can review shared mobile architecture?",
  "Who worked on the mobile redesign?",
  "Who is leading the mobile redesign?",
  "Which project covers app navigation?",
  "Who owns the customer identity refresh?",
  "Who leads login modernization?",
  "Who owns the Partner Onboarding API?",
  "Partner API owner?",
  "Who manages partner credentials?",
  "Who reviews API gateway policy exceptions?",
  "Who handles OAuth scope changes?",
  "Who approves Snowflake access requests?",
  "How do I request production data access?",
  "Who manages Snowflake roles?",
  "Who maintains data contracts?",
  "Who knows dbt?",
  "Which team owns data lineage?",
  "Which team owns customer mobile?",
  "What does Claims Platform manage?",
  "Who is in Cloud Governance?",
  "Which team handles partner integrations?",
  "What does Data Enablement own?",
  "Who is the backup?",
  "Who is the primary contact?",
  "Which team owns it?",
  "What evidence do you have?",
  "What other systems does this team manage?",
  "Who should I ask next?",
  "Customer onboarding owner?",
  "Who knows React?",
  "Which team manages production access?",
  "Thanks",
  "Bye",
];
